"use strict";
// login
export const loginTypeConstants = {
  SIGN_UP: "SIGN_UP",
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  UPDATE_CURRENT_USER_INFO: "UPDATE_CURRENT_USER_INFO",
  GET_VCODE: "GET_VCODE",
  RESET_PASSWORD: "RESET_PASSWORD",
  FETCH_USER_ROLE: "FETCH_USER_ROLE",
  // change user info
  CHANGE_USER_INFO: "CHANGE_USER_INFO",
  CHANGE_USER_INFO_SUCCESS: "CHANGE_USER_INFO_SUCCESS",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  SEND_FEEDBACK: "SEND_FEEDBACK",
  FETCH_ALL_DATA: "FETCH_ALL_DATA"
};

// message
export const messageTypeConstants = {
  FETCH_MESSAGE: "FETCH_MESSAGE",
  FETCH_MESSAGE_FULFILLED: "FETCH_MESSAGE_FULFILLED",
  FETCH_NEW_MESSAGE_COUNT: "FETCH_NEW_MESSAGE_COUNT",
  UPDATE_NEW_MESSAGE_COUNT: "UPDATE_NEW_MESSAGE_COUNT",
  UPDATE_MESSAGE_ISREAD: "UPDATE_MESSAGE_ISREAD",
  HANDLE_FRIEND_REQUEST: "HANDLE_FRIEND_REQUEST",
  HANDLE_GROUP_REQUEST: "HANDLE_GROUP_REQUEST",
  HANDLE_COMPANY_JOIN_REQUEST: "HANDLE_COMPANY_JOIN_REQUEST",
  HANDLE_COMPANY_EXIT_REQUEST: "HANDLE_COMPANY_EXIT_REQUEST"
};

// template
export const templateTypeConstants = {
  // get list
  GET_TEMPLATES: "GET_TEMPLATES",
  GET_TEMPLATES_FULFILLED: "GET_TEMPLATES_FULFILLED",
  // edit
  SAVE_EDITING_TEMPLATE: "SAVE_EDITING_TEMPLATE",
  SAVE_EDITING_FIELD: "SAVE_EDITING_FIELD",
  CLEAR_EDITING_FIELD: "CLEAR_EDITING_FIELD",
  DUPLICATE_TEMPLATE: "DUPLICATE_TEMPLATE",
  PREVIEW_TEMPLATE: "PREVIEW_TEMPLATE",
  PREVIEW_TEMPLATE_BY_SELECT: "PREVIEW_TEMPLATE_BY_SELECT",
  CLEAR_EDITING_TEMPLATE: "CLEAR_EDITING_TEMPLATE",
  // service
  FETCH_USER_TEMPLATES: "FETCH_USER_TEMPLATES",
  FETCH_COMPANY_TEMPLATES: "FETCH_COMPANY_TEMPLATES",
  FETCH_COMPANY_TEMPLATES_FULFILLED: "FETCH_COMPANY_TEMPLATES_FULFILLED",
  FETCH_SYSTEM_TEMPLATES: "FETCH_SYSTEM_TEMPLATES",
  FETCH_SYSTEM_TEMPLATES_FULFILLED: "FETCH_SYSTEM_TEMPLATES_FULFILLED",
  FETCH_TEMPLATE_INFO: "FETCH_TEMPLATE_INFO",
  UPLOAD_USER_TEMPLATE: "UPLOAD_USER_TEMPLATE",
  UPLOAD_USER_TEMPLATE_SUCCESS: "UPLOAD_USER_TEMPLATE_SUCCESS",
  UPLOAD_COMPANY_TEMPLATE: "UPLOAD_COMPANY_TEMPLATE",
  UPLOAD_COMPANY_TEMPLATE_SUCCESS: "UPLOAD_COMPANY_TEMPLATE_SUCCESS",
  DELETE_USER_TEMPLATE: "DELETE_USER_TEMPLATE",
  DELETE_USER_TEMPLATE_SUCCESS: "DELETE_USER_TEMPLATE_SUCCESS",
  DELETE_COMPANY_TEMPLATE: "DELETE_COMPANY_TEMPLATE",
  DELETE_COMPANY_TEMPLATE_SUCCESS: "DELETE_COMPANY_TEMPLATE_SUCCESS",
  SHARE_TEMPLATE: "SHARE_TEMPLATE",
  COPY_TEMPLATE_ADD_TO_MINE: "COPY_TEMPLATE_ADD_TO_MINE",
  ADD_SYSTEM_TEMPLATE_TO_COMPANY: "ADD_SYSTEM_TEMPLATE_TO_COMPANY",
  CLEAR_TEMPLATE_REDUCER: "CLEAR_TEMPLATE_REDUCER",
  // 备份
  BACKUP_TEMPLATES: "BACKUP_TEMPLATES"
};

// report
export const reportTypeConstants = {
  // get list
  GET_REPORTS: "GET_REPORTS",
  GET_REPORTS_FULFILLED: "GET_REPORTS_FULFILLED",

  // edit
  INIT_REPORT: "INIT_REPORT",
  INIT_REPORT_IMMEDIATE: "INIT_REPORT_IMMEDIATE",
  PREVIEW_REPORT: "PREVIEW_REPORT",
  PREVIEW_REPORT_BY_SELECT: "PREVIEW_REPORT_BY_SELECT",
  CLEAR_EDITING_REPORT: "CLEAR_EDITING_REPORT",
  DUPLICATE_DATA: "DUPLICATE_DATA",
  // service
  FETCH_USER_REPORTS: "FETCH_USER_REPORTS",
  FETCH_COMPANY_REPORTS: "FETCH_COMPANY_REPORTS",
  FETCH_REPORT_INFO: "FETCH_REPORT_INFO",
  FETCH_COMPANY_REPORTS_FULFILLED: "FETCH_COMPANY_REPORTS_FULFILLED",
  SUBMIT_REPORT_BY_SHARE: "SUBMIT_REPORT_BY_SHARE",
  UPLOAD_USER_REPORT: "UPLOAD_USER_REPORT",
  UPLOAD_USER_REPORT_SUCCESS: "UPLOAD_USER_REPORT_SUCCESS",
  UPLOAD_COMPANY_REPORT: "UPLOAD_COMPANY_REPORT",
  UPLOAD_COMPANY_REPORT_SUCCESS: "UPLOAD_COMPANY_REPORT_SUCCESS",
  AUTO_UPLOAD_COMPANY_REPORT_DRAFT: "AUTO_UPLOAD_COMPANY_REPORT_DRAFT",
  DELETE_USER_REPORT: "DELETE_USER_REPORT",
  DELETE_USER_REPORT_SUCCESS: "DELETE_USER_REPORT_SUCCESS",
  DELETE_COMPANY_REPORT: "DELETE_COMPANY_REPORT",
  DELETE_COMPANY_REPORT_SUCCESS: "DELETE_COMPANY_REPORT_SUCCESS",
  SHARE_REPORT: "SHARE_REPORT",
  COPY_REPORT_ADD_TO_MINE: "COPY_REPORT_ADD_TO_MINE",
  CLEAR_REPORT_REDUCER: "CLEAR_REPORT_REDUCER"
};

// friend
export const friendTypeConstants = {
  GET_FRIENDS: "GET_FRIENDS",
  FETCH_FRIENDLIST: "FETCH_FRIENDLIST",
  GET_FRIENDLIST_SUCCESS: "GET_FRIENDLIST_SUCCESS",
  SELECT_FRIEND: "SELECT_FRIEND",
  ADD_FRIEND_BY_EMAIL: "ADD_FRIEND_BY_EMAIL",
  DELETE_FRIEND: "DELETE_FRIEND",
  DELETE_FRIEND_SUCCESS: "DELETE_FRIEND_SUCCESS",
  SEARCH_USER_BY_EMAIL: "SEARCH_USER_BY_EMAIL"
};

export const groupTypeConstants = {
  // group
  FETCH_GROUPS: "FETCH_GROUPS",
  FETCH_GROUPS_SUCCESS: "FETCH_GROUPS_SUCCESS",
  GET_GROUPS: "GET_GROUPS",
  GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
  CREATE_GROUP: "CREATE_GROUP",
  GET_GROUP_MEMBERS: "GET_GROUP_MEMBERS",
  GET_GROUP_MEMBERS_SUCCESS: "GET_GROUP_MEMBERS_SUCCESS",
  SELECT_GROUP: "SELECT_GROUP",
  CLEAR_GROUP_SELECT: "CLEAR_GROUP_SELECT",
  UPDATE_GROUP: "UPDATE_GROUP",
  JOIN_GROUP: "JOIN_GROUP",
  EXIT_GROUP: "EXIT_GROUP",
  TRANSFER_GROUP: "TRANSFER_GROUP",
  DELETE_USER: "DELETE_USER"
};
// company
export const companyTypeConstants = {
  FETCH_COMPANY_INFO: "FETCH_COMPANY_INFO",
  FETCH_COMPANY_INFO_FULFILLED: "FETCH_COMPANY_INFO_FULFILLED",
  FETCH_COMPANY_STAFF: "FETCH_COMPANY_STAFF",
  FETCH_COMPANY_STAFF_FULFILLED: "FETCH_COMPANY_STAFF_FULFILLED",
  CREATE_COMPANY: "CREATE_COMPANY",
  UPDATE_COMPANY: "UPDATE_COMPANY",
  UPDATE_STAFF_INFO: "UPDATE_STAFF_INFO",
  UPDATE_STAFF_INFO_SUCCESS: "UPDATE_STAFF_INFO_SUCCESS",
  JOIN_COMPANY: "JOIN_COMPANY",
  INVITE_fRIENDS_TO_COMPANY: "INVITE_fRIENDS_TO_COMPANY",
  QUIT_COMPANY: "QUIT_COMPANY"
};

export const dynamicTypeConstants = {
  FETCH_DYNAMIC: "FETCH_DYNAMIC",
  FETCH_DYNAMIC_FULFILLED: "FETCH_DYNAMIC_FULFILLED"
};
