'use strict';
export enum ActionTypes {
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT = 'LOGOUT',
  UPDATE_CURRENT_USER_INFO = 'UPDATE_CURRENT_USER_INFO',
  FETCH_ALL_DATA = 'FETCH_ALL_DATA',
}
