'use strict';
export enum ActionTypes {
  // common
  OPEN_ACTION_SHEET = 'OPEN_ACTION_SHEET',
  CLOSE_ACTION_SHEET = 'CLOSE_ACTION_SHEET',
  CLEAR_COMMON_REDUCER = 'CLEAR_COMMON_REDUCER',
  // personal
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT = 'LOGOUT',
  UPDATE_CURRENT_USER_INFO = 'UPDATE_CURRENT_USER_INFO',
  FETCH_ALL_DATA = 'FETCH_ALL_DATA',
}
