import {StyleSheet} from 'react-native';
import {DColors, DFontSize, FONT_FAMILY} from '../../common/styles';
import {
  deviceWidth, // 设备宽度
  setSizeWithPx, // 设置字体 px 转 dp
} from '../../common/utils';

export const styles = StyleSheet.create({
  // createTemplate
  container: {
    flex: 1,
    backgroundColor: '#F2F2F2',
    justifyContent: 'space-between',
  },
  titleBar: {
    marginHorizontal: 17,
    marginTop: 16,
    height: 52,
    backgroundColor: '#ffffff',
    borderRadius: 3,
    paddingHorizontal: 16,
  },
  templateTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    color: DColors.title,
    marginRight: setSizeWithPx(35),
    maxWidth: setSizeWithPx(900),
  },
  dataTemplateTitle: {
    width: deviceWidth,
    marginVertical: 5,
    paddingHorizontal: 17,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  reportNameWrap: {
    width: deviceWidth,
    height: 40,
    paddingHorizontal: 17,
    flexDirection: 'row',
    alignItems: 'center',
  },
  content: {
    flex: 1,
  },
  footerWrapper: {
    height: setSizeWithPx(170),
  },
  createSectionContainer: {
    height: 40,
    width: 40,
    position: 'absolute',
    right: 17,
    bottom: 80,
  },
  enterStyle: {
    width: 7,
    height: 12,
    marginLeft: 8,
    tintColor: '#B3B3B3',
  },
  btnSubmit: {
    height: 40,
    marginHorizontal: 17,
    marginVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DColors.mainColor,
  },
  addFieldContainer: {
    marginHorizontal: 17,
    height: 48,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 3,
    marginTop: 14,
    marginBottom: setSizeWithPx(80),
  },
  addElementText: {
    marginLeft: 12,
    fontSize: 16,
    color: '#1E9DFC',
  },
  tableFieldItemWrap: {
    marginHorizontal: (deviceWidth * 0.1) / 2,
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  modal: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
  modalTitleWrapper: {
    height: setSizeWithPx(125),
    backgroundColor: '#ffffff',
    borderTopLeftRadius: setSizeWithPx(24),
    borderTopRightRadius: setSizeWithPx(24),
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: DFontSize.c1,
    color: DColors.title,
  },
  modalSelectWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 16,
    height: 120,
  },
  button: {
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  modalSelectItem: {
    width: 56,
    alignItems: 'center',
  },
  modalSelectWrap: {
    width: deviceWidth - 12,
    marginHorizontal: 6,
    marginBottom: 10,
    borderRadius: 12,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  modalTitleRow: {
    height: 40,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f9f9f9',
  },
  modalCancelRow: {
    width: deviceWidth - 12,
    height: 50,
    marginHorizontal: 6,
    marginBottom: 6,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  modalSelectRow: {
    height: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#f9f9f9',
  },
  iconWrapper: {
    width: 56,
    height: 56,
    borderRadius: 28,
    marginBottom: 10,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  typeIcon: {
    width: setSizeWithPx(66),
    height: setSizeWithPx(66),
  },
  indicatorStyle: {
    backgroundColor: '#ffffff',
    width: setSizeWithPx(118),
    height: setSizeWithPx(8),
    marginLeft: setSizeWithPx(121),
  },
  labelStyle: {
    fontSize: setSizeWithPx(50),
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  inputFieldWrapper: {
    minHeight: setSizeWithPx(264),
    borderRadius: setSizeWithPx(24),
    marginTop: setSizeWithPx(52),
    marginHorizontal: (deviceWidth * 0.1) / 2,
    backgroundColor: '#ffffff',
  },
  sectionTitleView: {
    marginHorizontal: 17,
    height: 48,
    backgroundColor: '#ffffff',
    borderRadius: 3,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  fieldSectionTitleInput: {
    fontSize: 16,
    color: '#757575',
    flex: 1,
  },
  FieldDeleteWrapper: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  fieldTitleInput: {
    minWidth: 100,
    maxWidth: deviceWidth - 200,
    fontSize: 16,
    color: '#757575',
  },
  FieldWrap: {
    marginHorizontal: 17,
    marginTop: 8,
    backgroundColor: '#fff',
  },
  copyFieldBtn: {
    height: 33,
    borderTopColor: '#F1F1F1',
    borderTopWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  copyFieldBtnText: {
    fontSize: 16,
    color: DColors.mainColor,
  },
  fieldItem: {
    height: 48,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  linkFieldWrap: {
    // backgroundColor: "#ddd",
    marginBottom: 24,
  },
  fieldLink: {
    marginTop: -28,
    flexDirection: 'row',
    alignItems: 'center',
  },
  fieldLinkText: {
    fontSize: 12,
    color: DColors.mainColor,
  },
  fieldItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fieldItemRight: {
    maxWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  fieldTypeText: {
    fontSize: 16,
    color: '#757575',
  },
  fieldTitle: {
    fontSize: DFontSize.c1,
    color: DColors.title,
    marginHorizontal: setSizeWithPx(58),
    padding: 0,
  },
  fieldInput: {
    height: setSizeWithPx(112),
    borderRadius: setSizeWithPx(10),
    marginTop: setSizeWithPx(30),
    marginHorizontal: 20,
    marginBottom: setSizeWithPx(56),
    backgroundColor: '#f0f0f0',
  },
  questionDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: setSizeWithPx(30),
    marginBottom: setSizeWithPx(56),
    paddingLeft: setSizeWithPx(58),
  },
  signaturePadView: {
    marginTop: setSizeWithPx(30),
    marginBottom: setSizeWithPx(56),
    alignItems: 'center',
    justifyContent: 'center',
  },
  questionIMGDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: setSizeWithPx(192),
    height: setSizeWithPx(192),
    borderRadius: setSizeWithPx(8),
    marginTop: setSizeWithPx(30),
    marginLeft: setSizeWithPx(58),
    marginBottom: setSizeWithPx(56),
    backgroundColor: '#f0f0f0',
  },
  questionText: {
    color: DColors.content,
    marginLeft: setSizeWithPx(20),
  },
  selectionFooter: {
    height: setSizeWithPx(144),
    borderTopWidth: setSizeWithPx(2),
    borderTopColor: '#f2f2f2',
    paddingLeft: setSizeWithPx(56),
    paddingRight: setSizeWithPx(56),
    justifyContent: 'flex-end',
    alignItems: 'center',
    flexDirection: 'row',
  },
  optionItem: {
    height: setSizeWithPx(144),
    borderTopWidth: setSizeWithPx(2),
    borderTopColor: '#f2f2f2',
    paddingLeft: setSizeWithPx(56),
    // paddingRight: setSizeWithPx(56),
    alignItems: 'center',
    flexDirection: 'row',
  },
  optionCircle: {
    width: setSizeWithPx(46),
    height: setSizeWithPx(46),
    borderRadius: setSizeWithPx(24),
    borderWidth: 1,
    borderColor: '#ccc',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  optionBox: {
    width: setSizeWithPx(46),
    height: setSizeWithPx(46),
    borderWidth: 1,
    borderColor: '#ccc',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  optionInput: {
    flex: 1,
    marginLeft: setSizeWithPx(24),
  },
  subSelectOption: {
    height: setSizeWithPx(144),
    width: setSizeWithPx(180),
    position: 'absolute',
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabsContainer: {
    flex: 1,
    backgroundColor: '#F2F2F2',
  },
  tabBar: {
    height: 44,
    marginHorizontal: 17,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  deleteSectionWrap: {
    paddingHorizontal: 12,
  },
  tabBarItem: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  tabBarText: {
    fontSize: 14,
    color: '#757575',
  },
  activeTabLine: {
    width: '80%',
    minWidth: 40,
    height: 2,
    borderRadius: 1,
    marginTop: 6,
  },

  noticeBarWrap: {
    width: deviceWidth,
    zIndex: 999,
    position: 'absolute',
    top: 0,
  },

  // regulation
  switchView: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  switchText: {
    fontSize: 16,
    color: '#2E2E2E',
  },
  fieldPropsList: {
    backgroundColor: '#fff',
    paddingHorizontal: 17,
  },
  fieldPropsItemLine: {
    borderTopWidth: 1,
    borderTopColor: '#F2F2F2',
  },
  typeSelectView: {
    flex: 1,
  },
  typeSelectTitleView: {
    height: 52,
    paddingHorizontal: 17,
    justifyContent: 'center',
  },
  typeSelectTitle: {
    color: '#2E2E2E',
    fontSize: 20,
  },
  typeSelectList: {
    backgroundColor: '#fff',
  },
  normalTypeItem: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
  },
  typeCheckbox: {
    width: 48,
    paddingHorizontal: 17,
  },
  typeTextView: {
    width: deviceWidth - 48,
    height: 52,
    borderBottomColor: '#F2F2F2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 17,
  },
  typeText: {
    fontSize: 16,
    color: '#2E2E2E',
  },
  typeTips: {
    fontSize: 16,
    color: '#757575',
  },
  unSelect: {
    width: 16,
    height: 16,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#757575',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 17,
  },
  selected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#1E9DFC',
  },
  checkboxTypeItem: {},
  checkboxList: {marginLeft: 48},
  checkboxOption: {
    width: deviceWidth - 48,
    height: 52,
    borderBottomColor: '#F2F2F2',
    borderBottomWidth: 1,
    flexDirection: 'row',
  },
  removeOptionBtn: {
    width: 32,
    justifyContent: 'center',
  },
  checkboxOptionInput: {
    width: deviceWidth - 100,
    fontSize: 16,
    color: '#757575',
  },
  addOptionBtn: {
    height: 48,
    borderBottomColor: '#F2F2F2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addOptionText: {
    marginLeft: 12,
    fontSize: 16,
    color: '#1E9DFC',
  },
  tableField: {
    width: deviceWidth - 48,
    height: 52,
    borderBottomColor: '#F2F2F2',
    borderBottomWidth: 1,
    paddingRight: 17,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tableFieldLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tableFieldNameInput: {
    minWidth: 100,
    maxWidth: deviceWidth - 200,
    fontSize: 16,
    color: '#757575',
  },
  tableFieldRight: {
    maxWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },

  // collectData
  formLabel: {
    fontSize: DFontSize.c1,
    color: DColors.content,
    // marginBottom: setSizeWithPx(15)
  },
  formItemWrap: {
    backgroundColor: '#fff',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    height: 48,
    marginTop: 16,
    marginBottom: 32,
    // height: setSizeWithPx(120)
  },
  TextAreaWrap: {
    backgroundColor: '#fff',
    paddingHorizontal: 17,
    paddingVertical: 12,
    marginTop: 16,
    marginBottom: 32,
  },
  scanFieldWrap: {
    backgroundColor: '#fff',
    paddingHorizontal: 17,
    paddingVertical: 12,
    marginTop: 16,
    marginBottom: 32,
  },
  scanFieldIcon: {
    position: 'absolute',
    right: 17,
    bottom: 12,
  },
  scanFieldClose: {
    position: 'absolute',
    top: 60,
    left: 20,
    zIndex: 999,
    width: 20,
    height: 20,
    backgroundColor: '#fff',
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullNameGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
    paddingVertical: 2,
    height: 52,
    marginTop: 16,
    marginBottom: 32,
  },
  fullNameItem: {
    backgroundColor: '#fff',
    width: (deviceWidth - 48) / 2,
    height: 48,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  formTableWrapper: {
    minHeight: setSizeWithPx(264),
    borderRadius: setSizeWithPx(24),
    backgroundColor: '#ffffff',
  },
  formInput: {
    padding: 0,
    flex: 1,
    fontFamily: FONT_FAMILY,
    color: '#575757',
    fontSize: 14,
  },
  formCheckBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingLeft: setSizeWithPx(30),
    paddingRight: 17,
    minHeight: setSizeWithPx(140),
    backgroundColor: '#ffffff',
    marginTop: 16,
    marginBottom: 32,
  },
  formCheckBoxTextView: {
    paddingVertical: 5,
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  formCheckBoxText: {
    marginVertical: 3,
    fontSize: DFontSize.c1,
    color: DColors.title,
  },
  formItemWrapO: {
    marginTop: 16,
    marginBottom: 32,
    paddingLeft: setSizeWithPx(30),
    paddingRight: setSizeWithPx(30),
    height: setSizeWithPx(100),
    flexDirection: 'row',
    alignItems: 'center',
  },
  formItemWrapOText: {
    fontFamily: FONT_FAMILY,
    fontSize: 16,
    color: DColors.title,
    marginLeft: setSizeWithPx(30),
  },
  DPicker: {
    borderColor: 'blue',
    borderWidth: 2,
  },
  checkWrapper: {
    flexDirection: 'row',
    // flex: 1
    height: setSizeWithPx(120),
    alignItems: 'center',
  },
  unCheck: {
    width: setSizeWithPx(55),
    height: setSizeWithPx(55),
    borderWidth: 1,
    borderColor: '#ccc',
    marginRight: setSizeWithPx(20),
    borderRadius: 1,
  },
  check: {
    width: setSizeWithPx(55),
    height: setSizeWithPx(55),
    borderWidth: 1,
    marginRight: setSizeWithPx(20),
  },
  checkText: {
    fontSize: DFontSize.c1,
    color: DColors.title,
  },
  ModalStyle: {
    flex: 1,
    // position: "absolute",
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: setSizeWithPx(75),
    paddingRight: setSizeWithPx(75),
  },
  ModalContentStyle: {
    backgroundColor: '#ffffff',
    width: '100%',
    paddingLeft: setSizeWithPx(25),
    paddingRight: setSizeWithPx(25),
    paddingTop: setSizeWithPx(40),
    paddingBottom: setSizeWithPx(40),
    borderRadius: setSizeWithPx(5),
  },
  TableLine: {
    height: 1,
    backgroundColor: '#ccc',
  },
  table: {
    height: 48,
    marginLeft: 17,
    marginRight: 17,
    marginTop: 16,
    marginBottom: 32,
    paddingLeft: 17,
    paddingRight: 17,
    justifyContent: 'center',
    borderColor: '#ccc',
    borderWidth: 1,
  },
  container2: {
    height: 240,
    width: deviceWidth - 34,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 32,
  },
  map: {
    height: 240,
    width: deviceWidth - 34,
  },
});
